app:
  name: APP_NAME
config:
  provider: #remote config provider: etcd„ÄÅconsul
  endpoint:
  path:
  types: json
http:
  mode: debug
  host: 127.0.0.1
  port: 9090
grpc:
  host: 10.95.19.98
  port: 9000
consul:
  address: ${consul_addr}
jaeger:
  serviceName: test
  reporter:
    localAgentHostPort: "jaeger-agent:6831"
  sampler:
    type: const
    param: 1
log:
  filename: ../logs/test.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: true
mysql:
  db_name: test
  wdb:
    host: ${mysql_host}
    user: ${mysql_user}
    pass: ${mysql_pass}
  rdbs:
    - host: ${mysql_host}
      user: ${mysql_user}
      pass: ${mysql_pass}
